[meta]
title = "Django Text-to-Speech"
description = "Get started using Deepgram's Text-to-Speech with this Django demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
repository = "https://github.com/deepgram-starters/django-text-to-speech"
useCase = "Text-to-Speech"
language = "Python"
framework = "Django"
sdk = "5.3.2"

[build]
command = "make init"

[config]
DEEPGRAM_API_KEY = "YOUR_DEEPGRAM_API_KEY"

[dev]
command = "make dev"

[start]
command = "make start"
